rm -r */__pycache__
rm -r __pycache__
rm -r */.cph
rm -r */*/__pycache__
rm -r */*/.cph
rm -r */*/*/__pycache__
rm -r */*/*/.cph
rm -r */*/*/*/__pycache__
rm -r */*/*/*/.cph
rm -r saved
rm -r logs.txt
rm -r env